### ISSUE TITLE
Add support for banlurker

### ISSUE THREAD

**Issue by yakovyarmo** [NITEMAN/varnish-bites#5]
Add support for banlurker as used with drupal varnish module

**Comment by NITEMAN** [comment]
Do you mean fake headers to help the lurker? (as seen in https://www.drupal.org/node/1423560)

I don't know if this is still an issue in Varnish 4, any insights on this will be really appreciated.

Please confirm or directly submit a PR

**Comment by yakovyarmo** [comment]
I do think it is an issue in Varnish 3.
Except of adding the header you can also use the in the ban part.

**Comment by NITEMAN** [comment]
Now added, sorry for the delay
