### ISSUE TITLE
LAN client get 503 error

### ISSUE THREAD

**Issue by dzymail** [NITEMAN/varnish-bites#8]
I put site into maintenance mode, and used this template file.
When we access from WAN, everything is great.
But when i access server from LAN(192.168.xx.xx), I got: error 503 backend fetch error.
maybe my server has two different route/network.
how can we fix this?
i am using drupal 7 + varnish 4 + centos 7

**Comment by NITEMAN** [comment]
Hi, I [answered your question on drupal.org](https://www.drupal.org/node/2626330#comment-11142121)

Feel free to re-open, but please choose only a channel

Best regards
