### ISSUE TITLE
Getting Cache-Control max-age=0, no-cache issue

### ISSUE THREAD

**Issue by jgardezi** [NITEMAN/varnish-bites#9]
Hi @NITEMAN,

I have tried to use this template https://github.com/NITEMAN/varnish-bites/blob/master/varnish4/drupal-base.vcl template. It seem like it is not working. Is their any configuration I need to do in the template in order to make it work. Please let me know?

My drupal 7 setting are 

`
 $conf['cache_backends'][] = 'sites/all/modules/varnish/varnish.cache.inc'; $conf['cache_class_external_varnish_page'] = 'VarnishCache'; $conf['reverse_proxy'] = true; $conf['reverse_proxy_addresses'] = array('172.31.10.68'); $conf['reverse_proxy_header'] = 'HTTP_X_FORWARDED_FOR'; $conf['cache_lifetime'] = 0; $conf['page_cache_maximum_age'] = 21600; $conf['page_cache_invoke_hooks'] = false; 
`

The reply I got from curl -I http://stage.mysite.com/ is 
`
HTTP/1.1 200 OK
Date: Fri, 08 Jul 2016 05:06:32 GMT
Server: Apache
X-Content-Type-Options: nosniff
Cache-Control: max-age=0, no-cache, must-revalidate, post-check=0, pre-check=0
X-Content-Type-Options: nosniff
Content-Language: en
X-UA-Compatible: IE=edge
X-Generator: Drupal 7 (http://drupal.org)
Link: <http://stage.mysite.com/>; rel="canonical",<http://stage.mysite.com/>; rel="shortlink"
Vary: Accept-Encoding
X-Mod-Pagespeed: 1.9.32.14-0
Content-Type: text/html; charset=utf-8
X-Varnish-Cacheable: NO:Not Cacheable
X-Varnish: 163872
Age: 0
Via: 1.1 varnish-v4
X-Varnish-Cache: MISS
X-Varnish-Server: varnish
Connection: keep-alive
`

Please help me I am new to this.

Kind regards,
Javed Gardezi

**Comment by NITEMAN** [comment]
You have the clue in the response headers:

```
X-Varnish-Cacheable: NO:Not Cacheable
```

In the vcl code you can find when this header is injected: https://github.com/NITEMAN/varnish-bites/blob/master/varnish4/drupal-base.vcl#L817

So I guess your Drupal settings are not taking effect. You can verify that looking at Cache-Control header making a curl request directly to the webserver.
